package us.tacticaledge.telemetry.shipments.model;// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/pauld/Android/TelemetryTest/semantic-itv-telemetry/data/src/main/proto/shipment.proto

import io.objectbox.BoxStore;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.relation.ToOne;
import us.tacticaledge.telemetry.integration.Exclude;

@Entity
public final class ShipmentLocation {

    @Id
    long id;

    @Exclude
    public ToOne<Shipment> shipment;


    public Double latitude;


    public Double longitude;


    public String locationURI;


    public String created;


    public String lastModified;


    public String gridLocation;


    public String locationCode;


    public String name;

    public String city;

    public String state;

    public String country;

    public String dataSource;

    public Integer locationShard;

    public Double confidence;

    public Boolean keyLocation;

    /**
     * Used to resolve relations
     */
    @Internal
    transient BoxStore __boxStore;

    @Internal
    transient ToOne<Shipment> shipmentToOne;

    public ShipmentLocation(Double latitude, Double longitude, String locationURI, String created, String lastModified, String gridLocation, String locationCode, String name, String city, String state, String country, String dataSource, Integer locationShard, Double confidence, Boolean keyLocation) {
        this.latitude = latitude;
        this.longitude = longitude;
        this.locationURI = locationURI;
        this.created = created;
        this.lastModified = lastModified;
        this.gridLocation = gridLocation;
        this.locationCode = locationCode;
        this.name = name;
        this.city = city;
        this.state = state;
        this.country = country;
        this.dataSource = dataSource;
        this.locationShard = locationShard;
        this.confidence = confidence;
        this.keyLocation = keyLocation;
    }

    public ShipmentLocation() {
    }

    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public ShipmentLocation(long id, Double latitude, Double longitude, String locationURI, String created, String lastModified, String gridLocation, String locationCode, String name, String city, String state, String country, String dataSource, Integer locationShard, Double confidence,
            Boolean keyLocation, long uid) {
        this.id = id;
        this.latitude = latitude;
        this.longitude = longitude;
        this.locationURI = locationURI;
        this.created = created;
        this.lastModified = lastModified;
        this.gridLocation = gridLocation;
        this.locationCode = locationCode;
        this.name = name;
        this.city = city;
        this.state = state;
        this.country = country;
        this.dataSource = dataSource;
        this.locationShard = locationShard;
        this.confidence = confidence;
        this.keyLocation = keyLocation;
        this.shipmentToOne.setTargetId(uid);
    }


    @Override
    public String toString() {
        return "us.tacticaledge.telemetry.shipments.model.ShipmentLocation{" +
                "latitude=" + latitude +
                ", longitude=" + longitude +
                ", locationURI='" + locationURI + '\'' +
                ", created='" + created + '\'' +
                ", lastModified='" + lastModified + '\'' +
                ", gridLocation='" + gridLocation + '\'' +
                ", locationCode='" + locationCode + '\'' +
                ", name='" + name + '\'' +
                ", city='" + city + '\'' +
                ", state='" + state + '\'' +
                ", country='" + country + '\'' +
                ", dataSource='" + dataSource + '\'' +
                ", locationShard=" + locationShard +
                ", confidence=" + confidence +
                ", keyLocation=" + keyLocation +
                '}';
    }


//    /**
//     * To-one relationship, resolved on first access.
//     */
//    public us.tacticaledge.telemetry.shipments.model.Shipment getShipment() {
//        shipment = shipmentToOne.getTarget();
//        return shipment;
//    }
//
//
//    /**
//     * Set the to-one relation including its ID property.
//     */
//    public void setShipment(us.tacticaledge.telemetry.shipments.model.Shipment shipment) {
//        shipmentToOne.setTarget(shipment);
//        this.shipment = shipment;
//    }
}
