package us.tacticaledge.telemetry.shipments.model;  // Code generated by Wire protocol buffer compiler, do not edit.
// Source file: /Users/pauld/Android/TelemetryTest/semantic-itv-telemetry/data/src/main/proto/shipment.proto



import io.objectbox.BoxStore;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.TargetIdProperty;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.relation.ToOne;
import us.tacticaledge.telemetry.integration.Exclude;


@Entity
public final class ShipmentItem {

    @Id
    long id;

    @Exclude
    @TargetIdProperty("uid")
    public ToOne<Shipment> shipment;

    public String orderNumber;

    public Integer quantity;

    public Integer quantityDelivered;

    public Double weight;

    public Double volume;

    public String partNumber;

    public String description;

    public String shipmentItemURI;

    public String shipmentId;

    public String lastModified;

    public String created;

    public String dataSource;

    public String classOfSupply;

    public Double unitPrice;

    public Integer pendingQuantity;

    public String unitOfIssue;

    public String conditionCode;

    public Integer getQuantityRemaining() {

        if (quantity == null || quantityDelivered == null)
            return quantity;
        return quantity - quantityDelivered;
    }

    public Integer getUpdatedQuantityRemaining() {


        if (quantity == null || quantityDelivered == null)
            return quantity - (pendingQuantity == null ? 0 : pendingQuantity);
        return quantity - quantityDelivered - (pendingQuantity == null ? 0 : pendingQuantity);
    }

    /**
     * Used to resolve relations
     */
    @Internal
    transient BoxStore __boxStore;

    @Internal
    transient ToOne<Shipment> shipmentToOne;

    public ShipmentItem(String orderNumber, Integer quantity, Integer quantityDelivered, Double weight, Double volume, String partNumber, String shipmentItemURI, String shipmentId, String lastModified, String created, String dataSource, String description, String classOfSupply, String unitOfIssue, Double unitPrice) {
        this.orderNumber = orderNumber;
        this.quantity = quantity;
        this.quantityDelivered = quantityDelivered;
        this.weight = weight;
        this.volume = volume;
        this.partNumber = partNumber;
        this.shipmentItemURI = shipmentItemURI;
        this.shipmentId = shipmentId;
        this.lastModified = lastModified;
        this.created = created;
        this.dataSource = dataSource;
        this.description = description;
        this.classOfSupply = classOfSupply;
        this.unitOfIssue = unitOfIssue;
        this.unitPrice = unitPrice;
    }

    public ShipmentItem() {
    }

    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public ShipmentItem(long id, String orderNumber, Integer quantity, Integer quantityDelivered, Double weight, Double volume, String partNumber, String shipmentItemURI, String shipmentId, String lastModified, String created, String dataSource, String description, String classOfSupply, String unitOfIssue,
                        Double unitPrice, long uid) {
        this.id = id;
        this.orderNumber = orderNumber;
        this.quantity = quantity;
        this.quantityDelivered = quantityDelivered;
        this.weight = weight;
        this.volume = volume;
        this.partNumber = partNumber;
        this.shipmentItemURI = shipmentItemURI;
        this.shipmentId = shipmentId;
        this.lastModified = lastModified;
        this.created = created;
        this.dataSource = dataSource;
        this.description = description;
        this.classOfSupply = classOfSupply;
        this.unitOfIssue = unitOfIssue;
        this.unitPrice = unitPrice;
        this.shipmentToOne.setTargetId(uid);
    }

    @Override
    public String toString() {
        return "us.tacticaledge.telemetry.shipments.model.ShipmentItem{" +
                "orderNumber='" + orderNumber + '\'' +
                ", quantity=" + quantity +
                ", quantityDelivered=" + quantityDelivered +
                ", weight=" + weight +
                ", volume=" + volume +
                ", partNumber='" + partNumber + '\'' +
                ", description='" + description + '\'' +
                ", shipmentItemURI='" + shipmentItemURI + '\'' +
                ", shipmentId='" + shipmentId + '\'' +
                ", lastModified='" + lastModified + '\'' +
                ", created='" + created + '\'' +
                ", dataSource='" + dataSource + '\'' +
                ", description='" + description + '\'' +
                ", classOfSupply='" + classOfSupply + '\'' +
                ", unitOfIssue='" + unitOfIssue + '\'' +
                ", unitPrice=" + unitPrice +
                '}';
    }

//    /**
//     * To-one relationship, resolved on first access.
//     */
//    public ToOne<us.tacticaledge.telemetry.shipments.model.Shipment> getShipment() {
//        shipment = shipmentToOne.getTarget();
//        return shipment;
//    }
//
//    /**
//     * Set the to-one relation including its ID property.
//     */
//    public void setShipment(us.tacticaledge.telemetry.shipments.model.Shipment shipment) {
//        shipmentToOne.setTarget(shipment);
//        this.shipment = shipment;
//    }


}
